### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Arranmc182** [rhino-linux/unicorn#37]
**Rhino Linux Version:**
2023.2

**Describe the bug**
Position of Plank dock not persistent.

**Expected behavior**
you change the settings as normal and the dock will move just as expected but if you shutdown or restart the system on next boot the dock will end up back in the left hand default position, also using dconf Editor same thing happens it moves as expected but next boot its back to its default.

**Comment by ajstrongdev** [comment]
@oklopfer I thought this was fixed recently unless I'm mistaken?

**Comment by ajstrongdev** [comment]
Can confirm this has been solved: To modify your plank config, edit: `/usr/share/plank/docks.ini` with the changes you want

**Comment by Arranmc182** [comment]
> Can confirm this has been solved: To modify your plank config, edit: `/usr/share/plank/docks.ini` with the changes you want

so its not fully fixed as the GUI options are still broken and the ini file fix is only good if your a bit more of an advanced user, also this is the first mention iv found about doing it via the ini file so thanks for the heads up

**Comment by ajstrongdev** [comment]
> > Can confirm this has been solved: To modify your plank config, edit: `/usr/share/plank/docks.ini` with the changes you want
> 
> 
> 
> so its not fully fixed as the GUI options are still broken and the ini file fix is only good if your a bit more of an advanced user, also this is the first mention iv found about doing it via the ini file so thanks for the heads up

We did mention it on our discord. I plan to document a list of guides on our Wiki at some point. 

Unfortunately Plank has been left unmaintained for a while and so while the end goal of Unicorn is to utilise our own components, or fork others, this will take a while. 

The issue here is with Plank dock and not Rhino Linux unfortunately.

**Comment by Arranmc182** [comment]
> > > Unfortunately Plank has been left unmaintained for a while and so while the end goal of Unicorn is to utilise our own components, or fork others, this will take a while.

Ah man that sucks I but understand, so basically Plank either needs to be forked or a replacement is needed so could we not use Cairo-Dock and Docky by default?

**Comment by nicahokie** [comment]
This bug is enough reason to deter me from using the otherwise great unicorn desktop

**Comment by oklopfer** [comment]
@nicahokie To modify your plank config, edit: `/usr/share/plank/docks.ini` with the changes you want, then log out and log back in.

**Comment by ngocnha** [comment]
The list of items in ~/.config/docks.ini appears exactly as I arranged them before logging out, but the items displayed on the screen do not follow that arrangement; they still revert to their original default positions.

> @nicahokie To modify your plank config, edit: `~/.config/docks.ini` with the changes you want, then log out and log back in.
> 
> apologies, these are the updated instructions.

**Comment by ajstrongdev** [comment]
@ngocnha I've attempted to replicate your issue, by pinning discord to the dock, and then changing my `~/.config/docks.ini` to have `discord.dockitem` as the first item, however I cannot seem to replicate the issue that you are having, as the position is maintained upon logging out of the Unicorn session. Would you be able to share the output of `cat ~/.config/docks.ini` here?

**Comment by ngocnha** [comment]
This screenshot captures the customized Plank Dock and its associated configuration.

![image](https://github.com/user-attachments/assets/875adf55-36df-4e91-b452-8cbcc8bf6c0f)

```
[dock1]
current-workspace-only=false
dock-items=['00-uniLauncher.dockitem', '01-uniApps.dockitem', '02-uniDesktop.dockitem', '03-firefox.dockitem', '04-FileManager.dockitem', '05-codium.dockitem', '06-xfce4-terminal.dockitem', '07-org.rhinolinux.system.dockitem']
hide-mode='intelligent'
icon-size=48
pinned-only=false
position='left'
pressure-reveal=false
theme='rhinoplank'
zoom-enabled=true
zoom-percent=115
```

**Comment by ajstrongdev** [comment]
@ngocnha 

It seems to me that you have not modified the actual configuration file, but rather modified it graphically via drag-and-drop, is this correct or am I missing something? From what I can see, the `docks.ini` file seems identical to our default. If you wish for your changes to remain permanent, modify this file.

**Comment by ngocnha** [comment]
Yes, this is the result after I dragged and dropped the items, then logged out and logged back in.

**Comment by ajstrongdev** [comment]
@ngocnha That'll be the issue then. If you see the replies above, you will note that the fix is to directly modify your `~/.config/docks.ini` file instead. Drag-and-drop has been a known issue for a long while with plank dock unfortunately, and as plank is no longer maintained, does not seem to be receiving a fix any time soon
